[default_session]
# startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/.config"
startup_command = "nvim"

[[session]]
name = "notes"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes"
startup_command = "nvim"
